### ISSUE TITLE
Documentation incorrectly refers to 'Guid' for item where it should be 'GUID'

### ISSUE THREAD

**Issue by hdinthkld** [mmcdole/gofeed#100]
### Expected behaviour
When using item.Guid it should return the value of Guid

### Actual behaviour
Error is returned:
Item.Guid undefined (type *gofeed.Item has no field or method Guid, but does have GUID)

### Steps to reproduce the behaviour
1. Read from a feed
2. Attempt to access 'Guid' method

Note: Please include any links to problem feeds, or the feed content itself!
Documentation is incorrect on this github page:
https://github.com/mmcdole/gofeed

**Comment by mmcdole** [comment]
Thank you for the issue, should be corrected.
