### ISSUE TITLE
Add new iTunes elements

### ISSUE THREAD

**Issue by mmcdole** [mmcdole/gofeed#118]
https://theaudacitytopodcast.com/apples-ios-11-podcast-analytics-and-podcasting-spec-update-tap310/

Apple has added several new iTunes feed extension elements.  Need to make sure they are all present and being parsed correctly in the iTunes structs.

**Comment by VarmaMSP** [comment]
Hi @mmcdole,  Created a PR #130  with new fields added to Itunes item extension.

**Comment by mmcdole** [comment]
@VarmaMSP ty!
