### ISSUE TITLE
Image is not pulled when RSS feed is translated

### ISSUE THREAD

**Issue by ddaggHT** [mmcdole/gofeed#126]
### Expected behavior
When a Item in a channel has a image it should be populated in the Feed and returned

### Actual behavior
Image is not populated when going through the rss parser nor is it a part of the struct

### Steps to reproduce the behavior
Read in a RSS feed with a channel and item containing a Image tag and no image URL will be populated

Note: Please include any links to problem feeds, or the feed content itself!

I personally have already developed the solution but I seem unable to create a branch and submit a PR to resolve it within the repo. I get a 403 response from github. But attached is my proposed solution.

![fix](https://user-images.githubusercontent.com/31410162/65268949-318a6f00-dae6-11e9-9d32-73bf425dd552.PNG)

**Comment by ddaggHT** [comment]
For got to Fork the repo. Rookie mistake....

**Comment by mmcdole** [comment]
@ddaggHT I struggle with this because according to the RSS specification, `item` doesn't have an `image` element.

I've thought about a perhaps dropping all elements that are part of the default namespace, but not technically valid to the RSS spec in the `extensions` element.
