### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by creekorful** [mmcdole/gofeed#143]
Hello @mmcdole,

Do you have any idea if/when a new release will be available?

I'm packaging your library on Debian, and the binary _ftest_ removed in this [commit](https://github.com/mmcdole/gofeed/commit/aaa570041b9e1faf7433ab0e299d26ca2549023f) is causing me trouble.
While I can remove it for the Debian package it would be better if I can just use a newly tagged clean version.

Have you any release planned?

Thank in advance

**Comment by mmcdole** [comment]
@creekorful just cut a new release.

Thanks!
