### ISSUE TITLE
c.Args()[0] (type cli.Args does not support indexing)

### ISSUE THREAD

**Issue by garlicgit** [mmcdole/gofeed#152]
Error on compile:

./rssfeed.go:25:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in slice literal:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
./rssfeed.go:31:13: cannot use func literal (type func(*cli.Context)) as type cli.ActionFunc in assignment
./rssfeed.go:38:22: invalid operation: c.Args()[0] (type cli.Args does not support indexing)

**Comment by skuzzymiglet** [comment]
This not a gofeed issue, please close it
