### ISSUE TITLE
"Failed to detect feed type" for many sites.

### ISSUE THREAD

**Issue by livelace** [mmcdole/gofeed#162]
### Expected behavior

Feeds should be read.

### Actual behavior

Failed to detect feed type

### Steps to reproduce the behavior

Read feed as usual. Dont' work:

https://zebra-tv.ru/rss
https://yarnovosti.com/feed/
https://yarreg.ru/feed
http://www.volgograd.ru/news/rss/
https://www.hibiny.com/news/rss.php
...

Note: Please include any links to problem feeds, or the feed content itself!

**Comment by JianRuHong** [comment]
I have the same problem

**Comment by livelace** [comment]
Hm, It seems the problem has already been solved in other repos.
https://github.com/skuzzymiglet/gofeed/blob/99fdea73ea8d81dbaaa45050e435924f1dbc7478/detector.go#L45

**Comment by livelace** [comment]
UP. It's already in master branch. Closed.
