### ISSUE TITLE
Content parsed into Description

### ISSUE THREAD

**Issue by gonejack** [mmcdole/gofeed#173]
I got a feed `https://www.williamlong.info/rss.xml` that `gofeed` would parse it's article content as description and content == ""

![image](https://user-images.githubusercontent.com/2720676/110203672-6e991b80-7eaa-11eb-9766-893ab8cf928a.png)

**Comment by gonejack** [comment]
```golang
package main

import (
	"fmt"
	"github.com/mmcdole/gofeed"
)

func main() {
	feed, _ :=gofeed.NewParser().ParseURL("https://www.williamlong.info/rss.xml")

	fmt.Println("content:", feed.Items[0].Content)
	fmt.Println("description:", feed.Items[0].Description)
}
```

**Comment by rodmcelrath** [comment]
There are no 'content' fields in that feed.  Only descriptions. I think it's functioning to spec.

**Comment by mmcdole** [comment]
@gonejack based on @rodmcelrath's comment, I'm going to close this issue.  Re-open if you feel something is incorrect.
