### ISSUE TITLE
Don't skip elements that are not part of the spec

### ISSUE THREAD

**Issue by microo8** [mmcdole/gofeed#174]
### Expected behavior
Elements or it's content are saved to `item.Custom[elementName] = elementContent`

So that that the CustomTranslator can pick up the fields and do something with it.

### Actual behavior
Elements that are not defined by the spec are just skipped https://github.com/mmcdole/gofeed/blob/1850ec19c3f1274cc77fad42a05c39d8eea701de/rss/parser.go#L285

**Comment by sjawaji** [comment]
@mmcdole - raised a pull request for this.  Please let me know if any changes are required.

**Comment by sjawaji** [comment]
@microo8 - this is now resolved.  My PR is merged.  You can try and let me know.

**Comment by microo8** [comment]
thanks that's great. I think it will work
