### ISSUE TITLE
Failed to detect feed type:http://www.dailytelegraph.com.au/feed/

### ISSUE THREAD

**Issue by meszaroszoltan** [mmcdole/gofeed#181]
Hello,

could you please look into it why this feed is considered invalid / unparsable ?
http://www.dailytelegraph.com.au/feed/

**Comment by Necoro** [comment]
That one was tricky:
`wget -O - https://www.dailytelegraph.com.au/feed` outputs the expected feed.
But when looking at all the redirects:
```
--2021-06-15 00:12:20--  https://www.dailytelegraph.com.au/feed/
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving www.dailytelegraph.com.au (www.dailytelegraph.com.au)... 23.3.64.134
Connecting to www.dailytelegraph.com.au (www.dailytelegraph.com.au)|23.3.64.134|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://www.dailytelegraph.com.au/remote/check_cookie.html?url=https%3a%2f%2fwww.dailytelegraph.com.au%2ffeed%2f [following]
--2021-06-15 00:12:20--  https://www.dailytelegraph.com.au/remote/check_cookie.html?url=https%3a%2f%2fwww.dailytelegraph.com.au%2ffeed%2f
Reusing existing connection to www.dailytelegraph.com.au:443.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://www.dailytelegraph.com.au/feed/ [following]
```
one gets the idea: Cookies.

And thus:
`wget --no-cookies -O - https://www.dailytelegraph.com.au/feed/` returns an HTML site that states that cookies need to be enabled.

Alternatives:
1. As cookies and RSS in combination make no sense, one should contact the Daily Telegraph and make them correct their broken implementation
2. Make gofeed support cookies: In `parser.go#ParseURLWithContext`:
```go
if client.Jar, err = cookiejar.New(nil); err != nil {
	return
}
```
3. Use your own `http.Client` and call `parse.Parse` with the result.

@mmcdole: How do you feel about this?

**Comment by mmcdole** [comment]
I agree @Necoro -- this is probably outside of what I'd consider normal.  For this, I'd do as you suggested and have them create their own http.Client with this behavior.
