### ISSUE TITLE
XML syntax error on line 3131: illegal character code U+001C

### ISSUE THREAD

**Issue by jdiaz** [mmcdole/gofeed#183]
### Expected behavior
Successful parse
### Actual behavior
Throws error
### Steps to reproduce the behavior
```go
fp := gofeed.NewParser()
url := "https://gcollazo.com/feed/"
feed, err := fp.ParseRSSFeed(url)
if err != nil {
  fmt.Println(err) // // XML syntax error on line 3131: illegal character code U+001C
}
```

Note: Please include any links to problem feeds, or the feed content itself!

**Comment by Necoro** [comment]
There is an encoding issue in the feed:

`<td>Recibí confirmación de que el reporte fue recibido y que se trabajaría de inmediato`

Firefox' RSS reader fails as well...

**Comment by jdiaz** [comment]
Thanks!
