### ISSUE TITLE
Failed to match this url:https://rss.netkeiba.com/?pid=rss_netkeiba&site=netkeiba

### ISSUE THREAD

**Issue by UniverseOfTomorrow** [mmcdole/gofeed#186]
### Steps to reproduce the behavior

Note: Please include any links to problem feeds, or the feed content itself!

**Comment by cristoper** [comment]
I just tried and that link is parsing fine for me with gofeed. Possibly an intermittent problem with that feed being malformed?

It does currently validate (though its items do not have GUIDs):
https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Frss.netkeiba.com%2F%3Fpid%3Drss_netkeiba%26site%3Dnetkeiba

**Comment by mmcdole** [comment]
Closing this issue per @cristoper 's comment.  Please re-open if you still see an issue.
