### ISSUE TITLE
README.md flow diagram flaw

### ISSUE THREAD

**Issue by leonardinius** [mmcdole/gofeed#19]
![](https://raw.githubusercontent.com/mmcdole/gofeed/master/docs/sequence.png)! seems to have confused Atom and RSS feeds.

I believe RSS feeds is being parsed by RSS parser, not Atom.

**Comment by mmcdole** [comment]
@leonardinius nice catch!  I'll regenerate the diagram image.

**Comment by mmcdole** [comment]
Should be fixed now!  Thanks
