### ISSUE TITLE
Support for comments tag in feed Item

### ISSUE THREAD

**Issue by piraces** [mmcdole/gofeed#198]
### Expected behavior

The `gofeed.Item` should have an entry for the `<comments>` tag, which its in the [RSS 2  specification](https://validator.w3.org/feed/docs/rss2.html#hrelementsOfLtitemgt), in order to extract and parse that content.

### Actual behavior

There is no actual way to extract the `<comments>` tag if available in the feed item.

### Steps to reproduce the behavior

Example with [https://stacker.news/rss](https://stacker.news/rss):
- Each item has a comment item and its not availiable in any entry of the `feed.Item`

![Example of parsed item](https://user-images.githubusercontent.com/11027628/216830401-b7e64d5f-b6f1-4378-ae3c-de161d32d76f.png)

**Comment by mmcdole** [comment]
@piraces thanks for this report.  I'll fix this ASAP.  

Unless you want to push an MR for the new field, and updates to rss/parser.go, rss/parser_test.go, parser.go, and the translator.go.

**Comment by piraces** [comment]
Thanks @mmcdole , nowadays am I little bit busy but I can attempt to do so 👍

**Comment by piraces** [comment]
Sorry for the confusion, this it's already implemented and I was wrong on the initial assumption... the `rss/feed.go` already has the `comments` mapping and the problem is on my side (since in atom feeds the is no such property). I will close the issue 👍
