### ISSUE TITLE
These links cannot be resolved

### ISSUE THREAD

**Issue by HeyDorvin** [mmcdole/gofeed#207]
### Expected behavior
Support parsing.
### Actual behavior
Failed to parse.
Failed to detect feed type: https://www.bleepingcomputer.com/feed/ https://www.ghacks.net/feed
XML syntax error: https://3gstudent.github.io/3gstudent.github.io/feed.xml ​https://kingx.me/feed.xml ​https://labs.watchtowr.com/rss ​https://www.synacktiv.com/feed/lastblog.xml ​https://ssd-disclosure.com/feed/

Although there are a few parts that do not support parsing, it has been done very well and hope to continue improving in the future.

**Comment by mmcdole** [comment]
@HeyDorvin 

I tested a few of these...

Feed 1: https://www.bleepingcomputer.com/feed/

The feed parses fine.  

However, the above feed is being protected by Cloudflare WAF.  If you download it manually from the browser, and then parse the feed, it parses fine.  This means anti-bot protection from Cloudflare is likely stopping the requests Gofeed makes.  I suggest you attempt to change the `User-Agent` settings in the Parser settings and see if it allows the request to go through.  

This worked form me:

```
curl https://www.bleepingcomputer.com/feed/ > feed.xml
./ftest feed.xml
```

Feed 2: https://www.ghacks.net/feed

This feed parses fine.

 ```
./ftest https://www.ghacks.net/feed
```

Feed 3: https://3gstudent.github.io/3gstudent.github.io/feed.xml

This feed URL returns a 301 `Permanently Moved` error.  The page it redirects to is an HTML page, not an RSS page.  However, if you use the following URL, it parses fine: https://3gstudent.github.io/atom.xml

**Comment by mmcdole** [comment]
I'll try to look at the others when I have some time.  But if you get a chance, try downloading them manually and parsing.

**Comment by HeyDorvin** [comment]
> I'll try to look at the others when I have some time. But if you get a chance, try downloading them manually and parsing.

Thank you for your reply. I didn't consider the error carefully when I saw it, and I didn't expect it to be because of these reasons.
