### ISSUE TITLE
XML syntax - illegal character code U+000C

### ISSUE THREAD

**Issue by pagedegeek** [mmcdole/gofeed#25]
### Expected behavior
Parse content

### Actual behavior
Check http://blog.octo.com/category/architecture-et-technologies/feed/
error in channel: XML syntax error on line 574: illegal character code U+000C
XML syntax error on line 574: illegal character code U+000C

**Comment by mmcdole** [comment]
@pagedegeek still narrowing down what the problem character is.  Something in the content of that element is terminating the CDATA section.  Will report back when I can narrow it down further.

**Comment by mmcdole** [comment]
I've also opened up #27 as I notice I must have recently introduced a regression when parsing CDATA sections.

**Comment by mmcdole** [comment]
@pagedegeek can you retest against the latest in the master branch?  I've made an attempt at stripping illegal characters from the stream before parsing.

**Comment by pagedegeek** [comment]
it's ok :) thank you !
