### ISSUE TITLE
Unable to parse feeds with a  BOM prefix

### ISSUE THREAD

**Issue by pagedegeek** [mmcdole/gofeed#26]
### Expected behavior
Feed parsed

### Actual behavior
http://www.larevuedudigital.com/feed/ -> Failed to detect feed type

**Comment by mmcdole** [comment]
@pagedegeek thanks for the bug report.  Looks like it is detects a text token before the tag token.

Let me work on a solution for the parsers/detector for this issue.

**Comment by mmcdole** [comment]
This should be fixed in PR #28.  I'm going to leave this issue open until I get unit tests in for this scenario though.
