### ISSUE TITLE
Copyright attribution and licensing required for XML unit tests

### ISSUE THREAD

**Issue by kurtmckee** [mmcdole/gofeed#47]
Hey Matthew, thanks for your help over on the feedparser issue tracker!

Mark Pilgrim claimed copyright over the feedparser XML unit tests released them under the 2-clause BSD license. In addition, I've spent the last six years cleaning up and adding new XML unit tests. However, I didn't see any copyright attribution nor the text of the 2-clause BSD license, both of which are mandatory in order to use the XML unit tests.

Would you update the gofeed documentation so that it clearly identifies both Mark Pilgrim and myself as the XML unit test copyright owners and identify that the unit test files are released under the terms of the 2-clause BSD license?

Thanks!

**Comment by mmcdole** [comment]
@kurtmckee no problem.  Thanks for pointing out the attribution issue.

I'd really like to avoid a dual license situation so I've deleted any test case that was ported from the feedparser project.  There were many in the project which I had created myself, but I didn't keep very good records identifying which were new and which were not, so to be safe, I purged them all.  

As the structure and specification of RSS and Atom are not Copyrighted by Mark Pilgrim, or yourself, I should be free to rewrite them sourcing the original specification documents.  I expect this to only take me a few days as the only tests I had ported to the project thus far were essentially the atom/rss feed elements enumerated with the various types of content they can contain.

None of feedparser's more valuable, and unique "illformed" xml tests were ported yet.  I'll have to fend for myself on those unfortunately.

As a side note, I've also updated the `Credits` section to include your name when referencing the feedparser library to recognize your contribution to the project.

**Comment by mmcdole** [comment]
Let me know if the deletion of these files in the `master` branch is sufficient, or if you would prefer me to perform a `git filter-branch` to permanently expunge them from my history.

**Comment by kurtmckee** [comment]
@mmcdole Thanks for the quick update! =)

I understand not wanting to deal with multiple licenses; I once read through all of the license information for Python itself and it is a big ball o' different licenses, author attributions, and oddities. And you're right, it's only the XML files included in feedparser that fall under copyright; Atom and RSS exist completely separately.

The deletion is sufficient, ``git filter-branch`` is pretty destructive for published branches.
