### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by skota** [mmcdole/gofeed#52]
### Expected behavior
Be able to run go feed

### Actual behavior
When i try to 'go build', i am seeing this error.
'package gofeed
	imports github.com/mmcdole/gofeed/internal/shared: use of internal package not allowed'

My go version is 'go version go1.5.1 darwin/amd64'

### Steps to reproduce the behavior
run go build

Note: Please include any links to problem feeds, or the feed content itself!
I am new to go. Did i miss anything?

**Comment by mmcdole** [comment]
Can you post the code where you are attempting to use the library?

**Comment by skota** [comment]
Hello, i just did a git clone and tried to build , is this meant to be used a different way? I am new to go ,perhaps i misunderstood how to use it?

**Comment by skota** [comment]
Please ignore this. I just re read the docs and i can use the library without  issues.

**Comment by mmcdole** [comment]
@skota ok.  If you need a quick easy way to test, I've included a test utilty.

Go to the `cmd/ftest/` directory, and a `go build` in there.

Then you can do the `ftest` command and hand it a file or feed URL to see how it parses.
