### ISSUE TITLE
HTTP errors are ignored

### ISSUE THREAD

**Issue by galdor** [mmcdole/gofeed#56]
### Expected behavior
When calling `ParseURL()` on a feed URL, if the server returns an error (e.g. 404), `ParseURL()` should return this error.

### Actual behavior
`ParseURL()` returns "Failed to detect feed type".

### Steps to reproduce the behavior
Simple example: use `ParseURL()` on http://boinkor.net/atom.xml (should return 404).

**Comment by mmcdole** [comment]
Fixed in #57.  Thanks!
