### ISSUE TITLE
http.Get can return non-nil response on non-nil error

### ISSUE THREAD

**Issue by RalphCorderoy** [mmcdole/gofeed#59]
Are you aware that http.Get can return a non-nil response that still needs closing even if err is non-nil as well? Not doing so leaks. http://devs.cloudimmunity.com/gotchas-and-common-mistakes-in-go-golang/index.html#close_http_resp_body

**Comment by mmcdole** [comment]
@RalphCorderoy I was not aware of that.  Can you look at PR #60 and let me know if that fixes the issue.

**Comment by mmcdole** [comment]
Further sources that point to that blog post being incorrect:

https://groups.google.com/forum/#!topic/golang-nuts/AidX-vUBLI0
