### ISSUE TITLE
ITunesFeedExtension.Image & ITunesItemExtension.Image

### ISSUE THREAD

**Issue by james-relyea** [mmcdole/gofeed#61]
I'm not 100% sure about this but I think the logic to parse the `<itunes:image>` element into `ITunesFeedExtension.Image` and `ITunesItemExtension.Image` may need an update.

All the feeds I'm parsing seem to be using a self-closing tag with the image URL contained in the `href` attribute. Currently the parser calls `parseTextExtension("image", extensions)` which returns an empty string.

I've modified a copy of gofeed I'm using to do something similar to the `<itunes:owner>` and `<itunes:category>` parsers:

```
func parseImage(extensions map[string][]Extension) (image string) {
	if extensions == nil {
		return
	}

	matches, ok := extensions["image"]
	if !ok || len(matches) == 0 {
		return
	}

	image = matches[0].Attrs["href"]
	return
}
```

Thanks so much for creating this library. It is fantastic.

**Comment by mmcdole** [comment]
Thanks for the issue!  Can you link to an example feed that I can test?

**Comment by james-relyea** [comment]
A few I tested with:
- http://www.cbc.ca/podcasting/includes/spark.xml<br/>
  (https://itunes.apple.com/ca/podcast/spark-from-cbc-radio/id263242885?mt=2)
- http://feeds.feedburner.com/JayandDan<br/>(https://itunes.apple.com/ca/podcast/the-jay-dan-podcast/id690863774?mt=2)
- http://feeds.gimletmedia.com/sciencevs<br/>(https://itunes.apple.com/us/podcast/science-vs-new-season/id1051557000?mt=2)

`<itunes:owner>` and `<itunes:category>` are to be parsing correctly, I believe.

**Comment by mmcdole** [comment]
@james-relyea should be in master now.  Let me know if you have any issues
