### ISSUE TITLE
Missing or incomplete values when parsing extensions

### ISSUE THREAD

**Issue by deepilla** [mmcdole/gofeed#78]
### Expected behavior

When parsing [this RSS feed](http://portal-api.thisisdistorted.com/xml/leftism), the `iTunesExt.Summary` field should be correctly populated for each item in the feed.

### Actual behavior

The `iTunesExt.Summary` field is blank for every item.

### Steps to reproduce the behavior

Parse the feed and inspect the resulting rss.Item values. You could also look at the translated gofeed.Item values.

### What's going on?

The problem appears to be in the [parseExtensionElement](https://github.com/mmcdole/gofeed/blob/master/internal/shared/extparser.go#L46) function. The function takes an XML node (in this case an `<itunes:summary>` tag) and uses it to create a new ext.Extension. It iterates over any child nodes and, if the child is of type text, [sets the Value of the new Extension](https://github.com/mmcdole/gofeed/blob/master/internal/shared/extparser.go#L83) to the text node's value. Note that if the parent node contains multiple child nodes of type text, only the final node's value is retained.

In [this particular feed](http://portal-api.thisisdistorted.com/xml/leftism), the item-level `<itunes:summary>` tags all contain three text nodes. The first and last are blank while the middle node holds the actual text. Currently this text is being overwritten with the final blank string.

### A possible cause

If you view the source for [the feed](http://portal-api.thisisdistorted.com/xml/leftism) you will see that there are extra line breaks around the text in the `<itunes:summary>` tags. These line breaks are not present on any other tags (all of which are being parsed correctly as far as I can tell). Perhaps the line breaks are causing the spurious text nodes.

### A possible fix

I fixed this in my vendored version of the code by changing [this line](https://github.com/mmcdole/gofeed/blob/master/internal/shared/extparser.go#L83):

`e.Value = strings.TrimSpace(p.Text)`

to this:

`e.Value += strings.TrimSpace(p.Text)`

But I'm not familiar with the project. Maybe this quick fix isn't the best approach. Let me know what you think (I can submit a PR if you'd like).

**Comment by mmcdole** [comment]
Looking into this.  Thanks for the report!

**Comment by deepilla** [comment]
Did you manage to reproduce this?

**Comment by mmcdole** [comment]
Yes, I was able to reproduce it.

I think your solution is a good one.  Perhaps we should only TrimSpace after we have aggregated all consecutive text nodes.  That way we won't be trimming space in the middle of a `CData` section that has line breaks.

**Comment by deepilla** [comment]
Sounds good. Do you want me to submit a PR or will you make the change?

**Comment by mmcdole** [comment]
I'll work on this today!

**Comment by mmcdole** [comment]
https://github.com/mmcdole/gofeed/pull/79 should hopefully address this issue.  Can you take a quick look?

**Comment by deepilla** [comment]
Yep, this is fixed in the `fix_extension_parsing` branch.

**Comment by mmcdole** [comment]
Merged.  Thanks for the report!
