### ISSUE TITLE
Zeroing not done for gofeed.Item.Author

### ISSUE THREAD

**Issue by captaincurrie** [mmcdole/gofeed#87]
Hello,

When a feed does not specify the author, the gofeed parser does not bother zeroing the
item.Author.Name and item.Author.Email fields.

### Expected behavior when author is not set in the feed
item.Author.Name -> ""

### Actual behavior
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6842a1]

goroutine 1 [running]:
main.main()
	/home/src/go/feedparser/main.go:52 +0x251

A feed which doesn't set the author field is the linux kernel feed "https://www.kernel.org/feeds/kdist.xml"

**Comment by mmcdole** [comment]
@captaincurrie are you sure the issue isn't that `item.Author` is a pointer to a `Person` object.

You must check if this `item.Author` is nil, before accessing the `Name` field.  The Name field should have the default value of empty string if `Author` is not nil.

**Comment by captaincurrie** [comment]
Oh. So it is by design. 

I assumed a better design would be to initialize the item.Author to a struct with empty strings for both
Person and Email

**Comment by mmcdole** [comment]
@captaincurrie It is so you can differentiate between a feed having an element or not.  For example, if you render a gofeed.Feed to JSON, you won't see an "Author" element in the rendered JSON if it was not present in the original feed.

It comes at the cost of having to nil check sub items before accessing them.

**Comment by captaincurrie** [comment]
Agreed. Thanks for all your work :+1:
