### ISSUE TITLE
RSS Feed data missing in 1.0.0-beta2

### ISSUE THREAD

**Issue by davidsbond** [mmcdole/gofeed#90]
### Expected behavior
When using v1.0.0-beta, requesting this feed `https://medium.com/feed/@ev` has the blog post content in:

```go
feed, _ := bc.parser.ParseURL("https://medium.com/feed/@ev")

for _, rss := range feed.Items {
    // For medium posts, the blog content is stored here.
    content := rss.Extensions["content"]["encoded"][0].Value
}
```
### Actual behavior
When using v1.0.0-beta2, accessing the same field causes errors, as the extension data is no longer present. 

### Steps to reproduce the behavior
Using the above code on v1.0.0-beta returns the RSS content. On v1.0.0-beta2, it does not.

**Comment by mmcdole** [comment]
@davidsbond I apologize for this backward incompatible change.

This was the result of us merging https://github.com/mmcdole/gofeed/pull/86, which was to fix bug https://github.com/mmcdole/gofeed/issues/31

You can now access this data via `Item.Content` directly.  Greater care should have been taken on my part to ensure that the old behavior remained as well however.

**Comment by davidsbond** [comment]
Thanks for the info! Have version locked to 1.0.0-beta but will try `Item.Content`
