### ISSUE TITLE
Timezones name do not effect the offset in PublishedParsed

### ISSUE THREAD

**Issue by Matt3o12** [mmcdole/gofeed#94]
`Sun, 06 Sep 2009 16:18:00 EST `is parsed as `2009-09-06 16:18:00 UTC` although it should be parsed as `2009-09-06 21:18:00 UTC` --> to say more precisely, the timezone EST is ignored. This is "default" behavior for go's `time.Parse()` method because timezone names are actually not well defined. You can learn more [here](https://news.ycombinator.com/item?id=10199812) but the short story is timezones are hard and annoying. 

I do not believe parsing the time as UTC is correct, either. IMO the library should do a 'best-effort' to parse the timezone as well as it can even if the timezone is incorrect in some cases because UTC is almost always incorrect. 

Go can be instructed to parse it by first parsing it normally and then using ParseInLocation on the parsed locale if found. This works pretty well in my experience if tzinfo is installed (it isn't on some distributions). But even then, we can still fall back to UTC. 

If have recently fixed this bug in another go rss library: SlyMarbo/rss but as it turned out, this library was missing some features and I decided to use this one. If you have interest in a patch for this problem, I would be happy to do it for you. I have already looked into the source code and I don't think it is difficult. 

You can see my patch in SlyMarbo/rss here: SlyMarbo/rss@bbde65d3b9d3e67c0dba33b68dca8096aa0bff2d

**Comment by mmcdole** [comment]
@Matt3o12 sorry for the delay in responding.   This makes sense to me and I think it would be a worth change!

I find this link also interesting regarding the Python Feedparser library: https://pythonhosted.org/feedparser/date-parsing.html

It talks a little about its timezone parsing it does as well.  Let me know how I can help.

**Comment by mmcdole** [comment]
@FedericoPonzi I'm considering offloading our date parsing to the following library:
https://github.com/araddon/dateparse

It's byte parser / state machine should be much faster than what we do today, and it looks like he appropriately handles timezone.

Could you try the above library on your example date and see what result you get for the parsed date?

**Comment by carlmjohnson** [comment]
I am also interested in this issue. I may issue a patch if I can.
