### ISSUE TITLE
Items are returned with empty GUIDs

### ISSUE THREAD

**Issue by awused** [mmcdole/gofeed#95]
### Expected behavior

A GUID should always be generated for every item.

Given an invalid but real world feed that only specifies title, description, link, and pubDate a GUID should still be generated. go-pkg-rss fell back to title + pubDate, and had further fallbacks.

### Actual behavior

Items with empty GUIDs, which are supposed to serve as unique identifiers, are returned.

### Steps to reproduce the behavior

An individual item:
<item>
  <title>TITLE</title>
      <description>DESCRIPTION</description>
  <link>https://www.novelupdates.com/link</link>
      <pubDate>Tue, 19 Jun 2018 02:11:17 +0000</pubDate>
</item>

These are personal feeds generated by https://www.novelupdates.com

**Comment by mmcdole** [comment]
I'm not certain it is appropriate for me to generate GUIDs for feeds that don't provide them themselves.  For one, GUID is an optional field in the RSS spec.  Secondly, the semantics for what might make an appropriate GUID can vary by feed type and domain.

For example, in podcast applications it is common to include the media file URL as an input into a GUID generation process.  This obviously wouldn't be applicable to all types of feeds.

I think it makes more sense for consumers of this library to implement their own GUID semantics.  The way people use these unique identifiers can have big implications to an application that uses them (as a key in a database, etc).  I want to faithfully reproduce feeds as best I can with this library.  If users want to modify the data returned from feeds they are free to do so.
